








function PlotStdCam(x,FOV)

xR=x(1:4);
xT=x(5:7);
R=Quat2Matrix(xR);

if nargin<2
  FOV=pi/2;
end

set(gca,'Color',[0,0,0],...
  'Visible','off',...
  'Projection','perspective',...
  'PlotBoxAspectRatioMode','manual',...
  'PlotBoxAspectRatio',[1,1,1],...
  'DataAspectRatioMode','manual',...
  'DataAspectRatio',[1 1 1],...
  'CameraUpVectorMode','manual',...
  'CameraUpVector',-R(:,3),...
  'CameraPositionMode','manual',...
  'CameraPosition',xT,...
  'CameraTargetMode','manual',...
  'CameraTarget',xT+R(:,1),...
  'CameraViewAngleMode','manual',...
  'CameraViewAngle',FOV*180/pi,...
  'Units','normalized',...
  'Position',[0 0 1 1]);

return;
